"use client";

import { useEffect, useState } from "react";
import api from "@/lib/api";
import { Event } from "@/types";
import { FileText, Download, Search, Calendar, Trophy } from "lucide-react";
import { LoadingSpinner } from "@/components/ui/LoadingSpinner";
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function ReportsPage() {
    const [events, setEvents] = useState<Event[]>([]);
    const [loading, setLoading] = useState(true);
    const [searchQuery, setSearchQuery] = useState("");

    useEffect(() => {
        fetchEvents();
    }, []);

    const fetchEvents = async () => {
        setLoading(true);
        try {
            // Add cache-busting timestamp
            const timestamp = new Date().getTime();
            const response = await api.get(`/events?_t=${timestamp}`);

            console.log("=== REPORTS PAGE DEBUG ===");
            console.log("Raw API Response:", response);
            console.log("Response Data:", response.data);
            console.log("Total Events:", response.data?.length);

            // Detailed inspection of first event
            if (response.data && response.data.length > 0) {
                const firstEvent = response.data[0];
                console.log("First Event Sample:", {
                    id: firstEvent.id,
                    title: firstEvent.title,
                    winners: firstEvent.winners,
                    winnersType: typeof firstEvent.winners,
                    winnersLength: firstEvent.winners?.length,
                    hasWinnersProperty: 'winners' in firstEvent
                });
            }

            // Filter only events that have winners
            const completedEvents = response.data.filter((event: any) => {
                const hasWinners = Array.isArray(event.winners) && event.winners.length > 0;
                console.log(`Event ${event.id} "${event.title}": winners=${event.winners?.length || 0}, hasWinners=${hasWinners}`);
                return hasWinners;
            });

            console.log("Filtered Events with Winners:", completedEvents);
            console.log("=========================");

            setEvents(completedEvents);
        } catch (error) {
            console.error("Failed to fetch events", error);
        } finally {
            setLoading(false);
        }
    };

    const handleDownloadReport = (event: Event) => {
        if (!event || !event.winners) return;

        const doc = new jsPDF();

        // Header
        doc.setFontSize(22);
        doc.setTextColor(40, 40, 40);
        doc.text("Raffle Draw Results", 14, 22);

        doc.setFontSize(12);
        doc.setTextColor(80, 80, 80);
        doc.text(`Event: ${event.title}`, 14, 32);
        doc.text(`Date: ${new Date(event.date).toLocaleDateString()}`, 14, 38);
        doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 44);

        // Table
        const tableBody = event.winners
            .sort((a, b) => a.gift.rank - b.gift.rank)
            .filter(w => w.gift && w.user) // Safety check
            .map(w => [
                `#${w.gift.rank}`,
                w.gift.name,
                w.user.name,
                w.user.location || '-',
                new Date(w.wonAt).toLocaleTimeString()
            ]);

        autoTable(doc, {
            head: [['Rank', 'Prize', 'Winner Name', 'Location', 'Time']],
            body: tableBody,
            startY: 50,
            theme: 'grid',
            headStyles: { fillColor: [66, 133, 244] }, // Blue header
            styles: { fontSize: 10, cellPadding: 4 },
            alternateRowStyles: { fillColor: [245, 247, 250] }
        });

        // Footer
        const pageCount = (doc as any).internal.getNumberOfPages();
        doc.setFontSize(8);
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.text('Confidential Report - Generated by Raffle System', 14, doc.internal.pageSize.height - 10);
            doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 25, doc.internal.pageSize.height - 10);
        }

        doc.save(`Raffle-Report-${event.title.replace(/\s+/g, '-')}.pdf`);
    };

    const filteredEvents = events.filter(event =>
        event.title.toLowerCase().includes(searchQuery.toLowerCase())
    );

    return (
        <div className="h-full flex flex-col">
            <div className="p-6 shrink-0 border-b border-gray-100/50">
                <div className="flex flex-col md:flex-row md:justify-between md:items-center gap-4">
                    <div>
                        <h1 className="text-2xl md:text-3xl font-bold text-gray-800" style={{ fontFamily: "Arial, sans-serif" }}>Reports & Results</h1>
                        <p className="text-gray-500 mt-1">Download official raffle draw results</p>
                    </div>
                    <div className="relative">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                        <input
                            type="text"
                            placeholder="Search reports..."
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            className="pl-10 pr-4 py-3 border border-gray-200 rounded-full w-full md:w-64 bg-white text-gray-900 placeholder-gray-500 focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 outline-none transition-all shadow-sm"
                        />
                    </div>
                </div>
            </div>

            <div className="flex-1 overflow-y-auto p-6 md:p-8 custom-scrollbar">
                {loading ? (
                    <div className="flex justify-center items-center py-20">
                        <LoadingSpinner size="lg" />
                    </div>
                ) : filteredEvents.length > 0 ? (
                    <div className="grid grid-cols-1 gap-4">
                        {filteredEvents.map(event => (
                            <div key={event.id} className="bg-white p-6 rounded-2xl border border-gray-100 hover:border-blue-200 hover:shadow-lg transition-all flex flex-col md:flex-row items-center justify-between gap-6 group">
                                <div className="flex flex-col sm:flex-row items-center gap-4 sm:gap-6 w-full text-center sm:text-left">
                                    <div className="w-16 h-16 rounded-2xl bg-blue-50 text-blue-600 flex items-center justify-center shrink-0 group-hover:scale-110 transition-transform duration-300">
                                        <Trophy className="w-8 h-8" />
                                    </div>
                                    <div className="w-full sm:w-auto">
                                        <h3 className="text-lg md:text-xl font-bold text-gray-900 mb-1">{event.title}</h3>
                                        <div className="flex items-center justify-center sm:justify-start gap-4 text-sm text-gray-500 flex-wrap">
                                            <span className="flex items-center gap-1.5 bg-gray-100 px-2.5 py-1 rounded-md">
                                                <Calendar className="w-4 h-4" />
                                                {new Date(event.date).toLocaleDateString()}
                                            </span>
                                            <span className="flex items-center gap-1.5 bg-green-50 text-green-700 px-2.5 py-1 rounded-md font-medium">
                                                <Trophy className="w-3.5 h-3.5" />
                                                {event.winners?.length || 0} Winners
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <button
                                    onClick={() => handleDownloadReport(event)}
                                    className="px-6 py-3 bg-gray-900 text-sm md:text-base text-white rounded-xl font-bold hover:bg-blue-600 hover:shadow-lg hover:-translate-y-0.5 transition-all flex items-center gap-2 whitespace-nowrap w-full md:w-auto justify-center"
                                >
                                    <Download className="w-5 h-5" />
                                    Download PDF
                                </button>
                            </div>
                        ))}
                    </div>
                ) : (
                    <div className="text-center py-20">
                        <div className="bg-gray-50 w-24 h-24 rounded-full flex items-center justify-center mx-auto mb-4">
                            <FileText className="w-12 h-12 text-gray-300" />
                        </div>
                        <h3 className="text-xl font-bold text-gray-800 mb-2">No Reports Available</h3>
                        <p className="text-gray-500 max-w-md mx-auto">
                            Reports are only available for events that have completed their raffle draw.
                            Complete a draw to generate a report.
                        </p>
                    </div>
                )}
            </div>
        </div>
    );
}
